apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: practical2
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: practical2
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: database
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_HOST: rabbitmq