# python slim
FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . ./app

EXPOSE 5006

ENV FLASK_APP=app/main.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5006", "--debug"]

