version: '3'
networks:
  rabbitmq_go_net:
    driver: bridge
services:
  rabbitmq:
    image: "rabbitmq:3.13-rc-management"
    container_name: rabbitmq_container
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  
    networks:
      - rabbitmq_go_net
  pika_example:
    container_name: pika_example
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net